site_name: QPet Lover
site_url: https://qpetlover.cn/
repo_url: https://github.com/QPetLover/qpetover.github.io
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: friendly
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/css/custom.css

extra:
  version:
    provider: mike
    default: latest
    alias: true

nav:
  - 主页: index.md
  - 文档:
    - 参与贡献: source/contribution.md
    - 快速开始: source/quickstart.md
    - 常见问题: source/faq.md
  - 相关链接: 
    - 下载链接: links/download.md
    - 项目地址: links/project.md
    